version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/python:3.11
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: scidb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: geheim

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: scidb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: geheim
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: geheim
      PGADMIN_CONFIG_SERVER_MODE: "True"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
      PGADMIN_CONFIG_SESSION_COOKIE_SAMESITE: "None"
      PGADMIN_CONFIG_SESSION_COOKIE_SECURE: "True"
      PGADMIN_CONFIG_PROXY_X_FOR_COUNT: "1"
      PGADMIN_CONFIG_PROXY_X_PROTO_COUNT: "1"
      PGADMIN_CONFIG_PROXY_X_HOST_COUNT: "1"
      PGADMIN_CONFIG_PROXY_X_PORT_COUNT: "1"
      PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT: "1"
      PGADMIN_CONFIG_CONTENT_SECURITY_POLICY: "default-src ws: wss: http: https: data: blob: 'unsafe-inline' 'unsafe-eval';"
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data-v2:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgres-data:
  pgadmin-data-v2:
